--- # Elasticsearch
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.8.2
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: ["master"]
      # only for dev https://elastic.co/guide/en/cloud-on-k8s/2.8/k8s-virtual-memory.html
      node.store.allow_mmap: false
  - name: data
    count: 1
    config:
      node.roles: ["data"]
      # only for dev https://elastic.co/guide/en/cloud-on-k8s/2.8/k8s-virtual-memory.html
      node.store.allow_mmap: false
  - name: client
    count: 1
    config:
      node.roles: []
      # only for dev https://elastic.co/guide/en/cloud-on-k8s/2.8/k8s-virtual-memory.html
      node.store.allow_mmap: false